server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

#==== mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.glozz.mechat.server.pojo
spring:
  datasource:
    url: jdbc://mysql:127.0.0.1/mechat
    username: root
    password: -pl,.;[=
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
