package com.glozz.mechat.server.mapper;

import com.glozz.mechat.server.pojo.ChatMsg;
import com.glozz.mechat.server.pojo.ChatMsgExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface ChatMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    long countByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int deleteByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int insert(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int insertSelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<ChatMsg> selectByExampleWithBLOBsWithRowbounds(ChatMsgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<ChatMsg> selectByExampleWithBLOBs(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<ChatMsg> selectByExampleWithRowbounds(ChatMsgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<ChatMsg> selectByExample(ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    ChatMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByExample(@Param("record") ChatMsg record, @Param("example") ChatMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByPrimaryKeySelective(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ChatMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByPrimaryKey(ChatMsg record);
}