package com.glozz.mechat.server.mapper;

import com.glozz.mechat.server.pojo.MechatUser;
import com.glozz.mechat.server.pojo.MechatUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    long countByExample(MechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int deleteByExample(MechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int insert(MechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int insertSelective(MechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<MechatUser> selectByExampleWithRowbounds(MechatUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    List<MechatUser> selectByExample(MechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    MechatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") MechatUser record, @Param("example") MechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByExample(@Param("record") MechatUser record, @Param("example") MechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByPrimaryKeySelective(MechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechat_user
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    int updateByPrimaryKey(MechatUser record);
}