package com.glozz.mechat.server.pojo;

import java.io.Serializable;
import java.util.Date;

public class FriendsRequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_request.id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_request.friends_request_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String friendsRequestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_request.send_user_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_request.accept_user_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String acceptUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends_request.request_date_time
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private Date requestDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends_request
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_request.id
     *
     * @return the value of friends_request.id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_request.id
     *
     * @param id the value for friends_request.id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_request.friends_request_id
     *
     * @return the value of friends_request.friends_request_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getFriendsRequestId() {
        return friendsRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_request.friends_request_id
     *
     * @param friendsRequestId the value for friends_request.friends_request_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setFriendsRequestId(String friendsRequestId) {
        this.friendsRequestId = friendsRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_request.send_user_id
     *
     * @return the value of friends_request.send_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_request.send_user_id
     *
     * @param sendUserId the value for friends_request.send_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setSendUserId(String sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_request.accept_user_id
     *
     * @return the value of friends_request.accept_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_request.accept_user_id
     *
     * @param acceptUserId the value for friends_request.accept_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setAcceptUserId(String acceptUserId) {
        this.acceptUserId = acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends_request.request_date_time
     *
     * @return the value of friends_request.request_date_time
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public Date getRequestDateTime() {
        return requestDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends_request.request_date_time
     *
     * @param requestDateTime the value for friends_request.request_date_time
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setRequestDateTime(Date requestDateTime) {
        this.requestDateTime = requestDateTime;
    }
}