package com.glozz.mechat.server.pojo;

import java.io.Serializable;

public class Friends implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.friend_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.my_user_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String myUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friends.my_friend_id
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private String myFriendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friends
     *
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.id
     *
     * @return the value of friends.id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.id
     *
     * @param id the value for friends.id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.friend_id
     *
     * @return the value of friends.friend_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.friend_id
     *
     * @param friendId the value for friends.friend_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.my_user_id
     *
     * @return the value of friends.my_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.my_user_id
     *
     * @param myUserId the value for friends.my_user_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setMyUserId(String myUserId) {
        this.myUserId = myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friends.my_friend_id
     *
     * @return the value of friends.my_friend_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public String getMyFriendId() {
        return myFriendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friends.my_friend_id
     *
     * @param myFriendId the value for friends.my_friend_id
     * @mbg.generated Sat Jul 20 22:55:38 CST 2019
     */
    public void setMyFriendId(String myFriendId) {
        this.myFriendId = myFriendId;
    }
}